import{S as L,i as g}from"./assets/vendor-7659544d.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const u of t.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",function(){const l=document.querySelector(".search-form"),n=document.querySelector(".gallery"),a=document.querySelector(".search-btn"),i=document.querySelector(".loader"),e="gallery-link";let t;a.disabled=!0,l.elements.query.addEventListener("input",function(){const r=this.value.trim();a.disabled=r===""}),l.addEventListener("submit",function(r){r.preventDefault();const s=r.target.elements.query.value.trim();s!==""&&(i.style.display="block",n.innerHTML="",u(s).then(c=>{i.style.display="none",y(c.hits),a.disabled=!0,t=new L(`.${e}`,{captionsData:"alt",captionDelay:250}),t.refresh(),t.on("show.simplelightbox")}).catch(c=>{i.style.display="none",d(`Error fetching images: ${c}`)}),r.target.elements.query.value="")});function u(r){const s="https://pixabay.com/api/",m=`?${new URLSearchParams({key:"42137546-386b5be41212ccd429cab5a80",q:r,image_type:"photo",orientation:"horizontal",safeSearch:!0})}`,p=s+m;return fetch(p).then(o=>{if(!o.ok)throw new Error(`Network response was not ok, status: ${o.status}`);return o.json()}).catch(o=>{throw d(`Error fetching images: ${o}`),o})}function f({webformatURL:r,largeImageURL:s,tags:c,likes:m,views:p,comments:o,downloads:b}){return`
  <a href="${s}" class="${e}">
     <figure>
      <img src="${r}" alt="${c}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <p class="image-item">Likes <span class="image-caption">${m}</span></p>
        <p class="image-item">Views <span class="image-caption">${p}</span></p>
        <p class="image-item">Comments <span class="image-caption">${o}</span></p>
        <p class="image-item">Downloads <span class="image-caption">${b}</span></p>
  </figcaption>
  </figure>
</a>`}function h(r){return r.map(f).join("")}function y(r){if(r.length===0){g.show({icon:"icon-close",messageSize:"16px",backgroundColor:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),a.disabled=!0;return}const s=h(r);n.innerHTML=s}});function d(l){g.show({message:l,backgroundColor:"#59A10D",progressBarColor:"#B5EA7C",icon:"icon-chek",...toastOptions})}
//# sourceMappingURL=commonHelpers.js.map
