import{S as y,i as h}from"./assets/vendor-7659544d.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",function(){const m=document.querySelector(".search-form"),n=document.querySelector(".gallery"),i=document.querySelector(".loader"),c="gallery-link";let e;m.addEventListener("submit",function(r){r.preventDefault(),i.style.display="block";const o=r.target.elements.query.value.trim();o!==""&&(n.innerHTML="",t(o).then(a=>{i.style.display="none",g(a.hits),e=new y(`.${c}`,{captionsData:"alt",captionDelay:250}),e.refresh(),e.on("show.simplelightbox")}).catch(a=>{i.style.display="none",console.error(`${a}`)}),r.target.elements.query.value="")});function t(r){const o="https://pixabay.com/api/",u=`?${new URLSearchParams({key:"42137546-386b5be41212ccd429cab5a80",q:r,image_type:"photo",orientation:"horizontal",safeSearch:!0})}`,p=o+u;return fetch(p).then(s=>{if(!s.ok)throw new Error(`Network response was not ok, status: ${s.status}`);return s.json()}).catch(s=>{throw console.error(`${s}`),s})}function l({webformatURL:r,largeImageURL:o,tags:a,likes:u,views:p,comments:s,downloads:d}){return`
  <a href="${o}" class="${c}">
     <figure>
      <img src="${r}" alt="${a}" class="gallery-image">
      <figcaption class="gallery__figcaption">
        <p class="image-item">Likes <span class="image-caption">${u}</span></p>
        <p class="image-item">Views <span class="image-caption">${p}</span></p>
        <p class="image-item">Comments <span class="image-caption">${s}</span></p>
        <p class="image-item">Downloads <span class="image-caption">${d}</span></p>
  </figcaption>
  </figure>
</a>`}function f(r){return r.map(l).join("")}function g(r){if(r.length===0){h.show({icon:"icon-close",messageSize:"16px",backgroundColor:"red",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=f(r);n.innerHTML=o}});
//# sourceMappingURL=commonHelpers.js.map
